module.exports = {
  HEALTH: "health",
  REGISTER: "register",
  LOGIN: "login",
  GET_PROFILE: "get_profile",
  LIST_USERS: "list_users",
  UPDATE_USER_STATUS: "update_user_status",
  CREATE_STORE_CATEGORY: "create_store_category",
  LIST_STORE_CATEGORIES: "list_store_categories",
  CREATE_DEAL_CATEGORY: "create_deal_category",
  LIST_DEAL_CATEGORIES: "list_deal_categories",
  CREATE_STORE: "create_store",
  LIST_STORES: "list_stores",
  GET_STORE: "get_store",
  CREATE_DEAL: "create_deal",
  LIST_DEALS: "list_deals",
  GET_DEAL: "get_deal",
  ADD_DEAL_IMAGE: "add_deal_image",
  CREATE_AD: "create_ad",
  LIST_ADS: "list_ads",
  CREATE_SUBSCRIPTION_PLAN: "create_subscription_plan",
  LIST_SUBSCRIPTION_PLANS: "list_subscription_plans",
  CREATE_NOTIFICATION: "create_notification",
  MY_NOTIFICATIONS: "my_notifications",
  MARK_NOTIFICATION_AS_READ: "mark_notification_as_read"
};
